import { MemberProfile, TraitVector } from "./types";

const baseVector = (): TraitVector => ({
  structuralDiscipline: 0,
  emotionalWarmth: 0,
  rhythmicDecisiveness: 0,
  expressiveDanger: 0,
  diplomaticInstinct: 0,
  practicalPreparedness: 0,
  charismaTheatricality: 0,
  introspectiveDepth: 0,
  stabilizingPresence: 0,
  playfulUnpredictability: 0,
});

export const members: Record<string, MemberProfile> = {
  angela: {
    id: "angela",
    name: "Angela",
    instrument: "Violin I",
    shortArchetype: "The Architecturally Radiant One",
    resultBody:
      "You lead not by volume but by conviction. Your instinct is to define direction, clarify standards, and align the room through sheer readiness. You chose presence over warmth, commitment over caution, and discipline over comfort. This is the profile of someone who can hold a sustained line while the ground shifts beneath them — and somehow make it look intentional.",
    greenFlags: [
      "Impeccable preparation under pressure",
      "Visible readiness that raises everyone's game",
      "Will actually read the program notes",
    ],
    redFlags: [
      "May over-prepare",
      "Secretly judges your bowings",
      "Standards that feel personal even when they're not",
    ],
    rehearsalRole: "The one who defines the direction",
    repertoireDate: "Late Beethoven by candlelight",
    targetVector: {
      ...baseVector(),
      structuralDiscipline: 0.85,
      emotionalWarmth: 0.7,
      rhythmicDecisiveness: 0.65,
      expressiveDanger: 0.45,
      diplomaticInstinct: 0.8,
      practicalPreparedness: 0.75,
      charismaTheatricality: 0.5,
      introspectiveDepth: 0.7,
      stabilizingPresence: 0.8,
      playfulUnpredictability: 0.3,
    },
  },
  justin: {
    id: "justin",
    name: "Justin",
    instrument: "Violin II",
    shortArchetype: "The Eloquently Undeniable One",
    resultBody:
      "You are the narrator the ensemble didn't know it needed. Your instinct is to frame, to contextualize, to explain what the piece is really trying to say before anyone else has found the words. You chose eloquence over presence, shape over weight, and meaning over raw conviction. You don't need the melody to matter — you need the story to land.",
    greenFlags: [
      "Can explain any piece in one sentence",
      "Beautifully delivered introductions from the stage",
      "Makes context feel like a gift, not a lecture",
    ],
    redFlags: [
      "May over-explain because context improves everything",
      "Emotionally available only when the narrative arc demands it",
      "Knows the through-line better than you do",
    ],
    rehearsalRole: "The one who explains what the piece is trying to say",
    repertoireDate: "Shostakovich at 2 AM, no talking after",
    targetVector: {
      ...baseVector(),
      structuralDiscipline: 0.7,
      emotionalWarmth: 0.55,
      rhythmicDecisiveness: 0.6,
      expressiveDanger: 0.6,
      diplomaticInstinct: 0.65,
      practicalPreparedness: 0.6,
      charismaTheatricality: 0.35,
      introspectiveDepth: 0.9,
      stabilizingPresence: 0.7,
      playfulUnpredictability: 0.45,
    },
  },
  benjamin: {
    id: "benjamin",
    name: "Benjamin",
    instrument: "Viola",
    shortArchetype: "The Harmonically Clairvoyant One",
    resultBody:
      "You hear the middle. While others chase the melody or anchor the bass, you are listening to the structural interior — the voicings, the hidden balances, the color that everyone else takes for granted. You chose taste over warmth, subtlety over spectacle, and the inner voice over the outer one. Your ear is tuned to the part of the music most people don't know exists.",
    greenFlags: [
      "Notices what everyone else overlooked",
      "Cultivated taste that elevates the ensemble's palette",
      "Will find the harmonic detail that changes the whole passage",
    ],
    redFlags: [
      "May get obsessed with color and voicing at the expense of momentum",
      "Secretly wants credit for the subtle detail no one noticed",
      "Has opinions about inner-voice balance that feel like philosophy",
    ],
    rehearsalRole: "The one who hears what is being overlooked",
    repertoireDate: "Brahms, window open, rain outside",
    targetVector: {
      ...baseVector(),
      structuralDiscipline: 0.6,
      emotionalWarmth: 0.65,
      rhythmicDecisiveness: 0.55,
      expressiveDanger: 0.35,
      diplomaticInstinct: 0.7,
      practicalPreparedness: 0.6,
      charismaTheatricality: 0.4,
      introspectiveDepth: 0.85,
      stabilizingPresence: 0.75,
      playfulUnpredictability: 0.3,
    },
  },
  russell: {
    id: "russell",
    name: "Russell",
    instrument: "Cello",
    shortArchetype: "The Gravitationally Essential One",
    resultBody:
      "You are the foundation the room didn't know it was standing on. Your instinct is to stabilize, to ground, to give every phrase something physical to rest on. You chose warmth over spectacle, depth over speed, and setup over spontaneity. You are the kind of player who adjusts one string and changes the whole room — and then quietly delights in having done it.",
    greenFlags: [
      "Physically grounded sound that anchors everything",
      "Genuinely curious about setup, materials, and resonance",
      "Makes the room feel stable simply by being in it",
    ],
    redFlags: [
      "May disappear into resonance and physical feel",
      "Has tried more string brands than anyone considers reasonable",
      "Emotionally available primarily through the instrument's body",
    ],
    rehearsalRole: "The one who makes everything hold together",
    repertoireDate: "Dvořák 'American' with the windows down",
    targetVector: {
      ...baseVector(),
      structuralDiscipline: 0.55,
      emotionalWarmth: 0.75,
      rhythmicDecisiveness: 0.7,
      expressiveDanger: 0.4,
      diplomaticInstinct: 0.5,
      practicalPreparedness: 0.8,
      charismaTheatricality: 0.35,
      introspectiveDepth: 0.6,
      stabilizingPresence: 0.9,
      playfulUnpredictability: 0.3,
    },
  },
};

export const memberList = Object.values(members);
